name: Build Icecam
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r26d
      - name: Build
        run: |
          mkdir build && cd build
          cmake -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK/build/cmake/android.toolchain.cmake \
                -DANDROID_ABI=arm64-v8a \
                -DANDROID_PLATFORM=android-30 \
                -DCMAKE_POLICY_DEFAULT_CMP0148=OLD \
                ../jni
          make
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: libicecam
          path: build/libicecam_hook.so
          