name: Build IceCam
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      
      - name: Setup NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r25c
          
      - name: Build with CMake
        run: |
          mkdir build && cd build
          # Указываем путь к папке jni, где лежит твой главный CMakeLists.txt
          cmake -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK/build/cmake/android.toolchain.cmake \
                -DANDROID_ABI=arm64-v8a \
                -DANDROID_PLATFORM=android-30 \
                ../jni
          make
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: icecam-library
          path: build/libicecam_hook.so
